name: automatization

on:
  push:
    branches:
      - "**"

jobs:
  Continuos-Integration:
    runs-on: self-hosted
    steps:
      - name: Build Started
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Build started.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Build Success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Build succeeded.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
