name: qa-build
on:
  push:
    branches:
      - qa
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  QA-Review:
    name: SonarCloud
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: QA-Scan
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Ha empezado el análisis de Sonar
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

